"use strict";
/* Texto de búsqueda sin acentos ni mayúsculas, para filtrar las filas de WO sin volver a armar el modal. */
const normBusca = s => String(s||"").normalize("NFD").replace(/[̀-ͯ]/g,"").toLowerCase();
function opcionesWOAsignacion(){return `<input id="gaBuscar" placeholder="Buscar WO, propiedad, unidad" autocomplete="off" style="margin:4px 0"><div style="display:flex;gap:14px;align-items:center;font-size:12px;margin-bottom:4px"><label style="display:flex;gap:5px;align-items:center"><input type="checkbox" id="gaSoloMarc"> Solo marcadas</label><span id="gaCnt" style="color:var(--faint)">0 marcadas</span></div><div id="gaLista" style="max-height:300px;overflow:auto">`+S.wos.filter(w=>w.estado!=="Canceled").map(w=>`<label class="gaRow" data-t="${esc(normBusca("WO-"+w.id+" "+P(w.prop).nombre+" "+U(w.unidad).num))}" style="display:flex;gap:7px;align-items:center;margin:6px 0"><input type="checkbox" class="gaWO" value="${w.id}"> WO-${w.id} · ${esc(P(w.prop).nombre)} ${esc(U(w.unidad).num)} <input type="number" class="gaMonto" data-wo="${w.id}" min="0" step="0.01" placeholder="monto asignado" style="margin-left:auto;width:125px"></label>`).join("")+"</div>";}
/* Reparto igual en centavos: el resto del redondeo cae en la última WO, así la suma siempre cuadra con el total. */
function repartirIgual(total,n){ const c=Math.round(total*100), base=Math.floor(c/n), r=Array(n).fill(base); r[n-1]+=c-base*n; return r.map(x=>x/100); }
/* Comprobante real (capturarFoto): un campo con su botón y la miniatura, sin rearmar el formulario. */
const campoRecibo = (etq) => `<div class="fld"><label>${etq}</label><div style="display:flex;align-items:center;gap:8px"><button type="button" class="btn sm" data-a="reciboFoto">📷 Foto</button><span id="recPrev">${miniRecibo(S._recibo)}</span></div></div>`;
const TIPOS_GASTO_FIJO = ["Luz","Agua","Renta","Internet","Contadores","Otros"];
Object.assign(ACC,{
  gastoCompartidoModal:()=>{ S._recibo=null; modal(`<div class="mh"><h3>Registrar gasto compartido</h3><p>El monto se reparte manualmente para conservar la utilidad correcta por WO.</p></div><div class="mb"><div class="fg c3"><div class="fld"><label>Tipo</label><select id="gaTipo"><option>Fuel</option><option>Accommodation</option><option>Office</option><option>Other</option></select></div><div class="fld"><label>Fecha <span class="req">*</span></label><input id="gaFecha" type="date" value="${HOY_SUP}"></div><div class="fld"><label>Monto total <span class="req">*</span></label><input id="gaTotal" type="number" min="0" step="0.01"></div></div><div class="fld"><label>Concepto <span class="req">*</span></label><input id="gaConcepto" placeholder="Ej. gasolina ruta lejana"></div><div class="fg c2"><div class="fld"><label>Vehículo — opcional</label><select id="gaVeh"><option value="">— no aplica —</option>${(S.vehiculos||[]).map(v=>`<option>${esc(v.nombre)}</option>`).join("")}</select></div>${campoRecibo("Comprobante")}</div><div class="fld"><label>Notas</label><input id="gaNotas"></div><div class="fld"><label>Asignar a estas WO</label><div class="note">El total de asignaciones debe ser igual al monto total. Si no asignas ninguna, queda como gasto general.</div><button type="button" class="btn sm" data-a="gastoRepartirIgual" style="margin-bottom:4px">Repartir igual</button>${opcionesWOAsignacion()}</div></div><div class="mf"><button class="btn" data-a="cm">Cancelar</button><button class="btn p" data-a="gastoCompartidoGuardar">Guardar gasto</button></div>`); },
  /* Reparte el total en partes iguales entre las WO marcadas; la asignación sigue siendo editable a mano. */
  /* Filtra por texto y por "solo marcadas" ocultando filas (no re-renderiza: se conservan montos y marcas); las ocultas marcadas siguen contando al guardar y al repartir. */
  gaFiltrar:()=>{const t=normBusca(val("gaBuscar")).split(/\s+/).filter(Boolean), solo=document.getElementById("gaSoloMarc").checked; document.querySelectorAll(".gaRow").forEach(r=>{r.style.display=t.every(x=>r.dataset.t.includes(x))&&(!solo||r.querySelector(".gaWO").checked)?"flex":"none";}); ACC.gaContar();},
  gaContar:()=>{const e=document.getElementById("gaCnt"); if(e) e.textContent=document.querySelectorAll(".gaWO:checked").length+" marcadas";},
  gastoRepartirIgual:()=>{const total=parseFloat(val("gaTotal")), marcadas=[...document.querySelectorAll(".gaWO:checked")]; if(!(total>0)){toast("Falta el monto","Escribe el monto total antes de repartir.","r");return;} if(!marcadas.length){toast("Marca las WO","Selecciona las WO entre las que se reparte.","r");return;} const partes=repartirIgual(total,marcadas.length); marcadas.forEach((e,i)=>{const m=document.querySelector(`.gaMonto[data-wo="${e.value}"]`); if(m) m.value=partes[i].toFixed(2);});},
  gastoCompartidoGuardar:()=>{const monto=parseFloat(val("gaTotal")), concepto=val("gaConcepto").trim(), fecha=val("gaFecha"); if(!(monto>0)||!concepto||!fecha){toast("Faltan datos","Concepto, fecha y monto son obligatorios.","r");return;} const asignaciones=[...document.querySelectorAll(".gaWO:checked")].map(e=>({wo:+e.value,monto:parseFloat(document.querySelector(`.gaMonto[data-wo="${e.value}"]`).value)||0})); const suma=asignaciones.reduce((n,a)=>n+a.monto,0); if(asignaciones.length&&Math.abs(suma-monto)>.009){toast("El reparto no cuadra",`Asignaste ${money(suma)} y el gasto es ${money(monto)}. Corrige los montos.`,"r");return;} S.gastosCompartidos.unshift({id:"GC"+(S.gastosCompartidos.length+1),tipo:val("gaTipo"),concepto,monto,fecha,vehiculo:val("gaVeh"),evidencia:!!S._recibo,foto:S._recibo||null,notas:val("gaNotas"),asignaciones,quien:S.usuario});cm();toast("✓ Gasto registrado",asignaciones.length?`Se repartió entre ${asignaciones.length} WO.`:"Quedó como gasto general sin repartir.","v");render();},
  vehiculoGastoModal:()=>{ S._recibo=null; modal(`<div class="mh"><h3>Gasto de vehículo — Gustavo</h3><p>Registra gasolina o mantenimiento; pasa al libro de Finanzas.</p></div><div class="mb"><div class="fg c2"><div class="fld"><label>Tipo</label><select id="vgTipo"><option>Fuel</option><option>Vehicle maintenance</option></select></div><div class="fld"><label>Vehículo <span class="req">*</span></label><select id="vgVeh">${(S.vehiculos||[]).map(v=>`<option>${esc(v.nombre)}</option>`).join("")}</select></div></div><div class="fg c2"><div class="fld"><label>Fecha <span class="req">*</span></label><input id="vgFecha" type="date" value="${HOY_SUP}"></div><div class="fld"><label>Monto <span class="req">*</span></label><input id="vgMonto" type="number" min="0" step="0.01"></div></div>${campoRecibo("Comprobante")}<div class="fld"><label>Notas</label><input id="vgNotas"></div></div><div class="mf"><button class="btn" data-a="cm">Cancelar</button><button class="btn p" data-a="vehiculoGastoGuardar">Registrar</button></div>`); },
  vehiculoGastoGuardar:()=>{const monto=parseFloat(val("vgMonto"));if(!(monto>0)){toast("Falta el monto","Registra un monto mayor a cero.","r");return;}S.gastosCompartidos.unshift({id:"GC"+(S.gastosCompartidos.length+1),tipo:val("vgTipo"),concepto:val("vgTipo")==="Fuel"?"Fuel loaded by Gustavo":"Vehicle maintenance",monto,fecha:val("vgFecha"),vehiculo:val("vgVeh"),evidencia:!!S._recibo,foto:S._recibo||null,notas:val("vgNotas"),asignaciones:[],quien:"Gustavo"});cm();toast("✓ Gasto de vehículo registrado","Ya aparece en Finanzas como salida general.","v");render();},
  /* Gastos fijos de oficina (luz, agua, renta…): salen en el libro de salidas y en el CSV como cualquier gasto, sin repartirse a WO. */
  gastoFijoModal:()=>{ if(soloLectura()) return; S._recibo=null; modal(`<div class="mh"><h3>Gasto fijo</h3></div><div class="mb"><div class="fg c2"><div class="fld"><label>Categoría</label><select id="gfTipo">${TIPOS_GASTO_FIJO.map(t=>`<option>${t}</option>`).join("")}</select></div><div class="fld"><label>Fecha <span class="req">*</span></label><input id="gfFecha" type="date" value="${HOY_SUP}"></div></div><div class="fg c2"><div class="fld"><label>Concepto</label><input id="gfConcepto" placeholder="Ej. recibo de agosto"></div><div class="fld"><label>Monto <span class="req">*</span></label><input id="gfMonto" type="number" min="0" step="0.01"></div></div>${campoRecibo("Comprobante — opcional")}</div><div class="mf"><button class="btn" data-a="cm">Cancelar</button><button class="btn p" data-a="gastoFijoGuardar">Guardar</button></div>`); },
  gastoFijoGuardar:()=>{ if(soloLectura()) return; const monto=parseFloat(val("gfMonto")), fecha=val("gfFecha"), tipo=val("gfTipo"); if(!(monto>0)||!fecha){toast("Faltan datos","Fecha y monto son obligatorios.","r");return;} S.gastosCompartidos.unshift({id:"GC"+(S.gastosCompartidos.length+1),tipo,concepto:val("gfConcepto")||tipo,monto,fecha,vehiculo:"",evidencia:!!S._recibo,foto:S._recibo||null,notas:"",asignaciones:[],fijo:true,quien:S.usuario});cm();toast("✓ Gasto fijo registrado",`${esc(tipo)} · ${money(monto)}. Ya sale en el libro de salidas.`,"v");render();},
  finanzasExportar:()=>{const rows=salidaFinanzas(); const csv=["Date,Source,Type,Description,Amount",...rows.map(x=>[x.fecha,x.origen,x.tipo,`"${String(x.concepto).replace(/"/g,'""')}"`,x.monto].join(","))].join("\n"); const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="cps-finance-outflows.csv";a.click();URL.revokeObjectURL(a.href);toast("✓ Archivo preparado","Descargaste el listado de salidas para contabilidad.","v");}
});
